// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB48WpHNBqlCI5WWtkTv_23r-eF2KmxhHQ',
    appId: '1:168563162134:web:371fa0d29834e8b4388937',
    messagingSenderId: '168563162134',
    projectId: 'flutter-test-69ab6',
    authDomain: 'flutter-test-69ab6.firebaseapp.com',
    databaseURL: 'https://flutter-test-69ab6-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-69ab6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAlQaPtV6ID2TrGoB2RWxwm0NsVnGEDsg',
    appId: '1:168563162134:android:208fad20c8f04348388937',
    messagingSenderId: '168563162134',
    projectId: 'flutter-test-69ab6',
    databaseURL: 'https://flutter-test-69ab6-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-69ab6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByxPzdI6bm46MTjsbIiRWl38ALgXlSrjQ',
    appId: '1:168563162134:ios:2e814637c471c691388937',
    messagingSenderId: '168563162134',
    projectId: 'flutter-test-69ab6',
    databaseURL: 'https://flutter-test-69ab6-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-69ab6.appspot.com',
    iosBundleId: 'com.enviaseo.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByxPzdI6bm46MTjsbIiRWl38ALgXlSrjQ',
    appId: '1:168563162134:ios:2e814637c471c691388937',
    messagingSenderId: '168563162134',
    projectId: 'flutter-test-69ab6',
    databaseURL: 'https://flutter-test-69ab6-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-69ab6.appspot.com',
    iosBundleId: 'com.enviaseo.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB48WpHNBqlCI5WWtkTv_23r-eF2KmxhHQ',
    appId: '1:168563162134:web:db50876bce2f8859388937',
    messagingSenderId: '168563162134',
    projectId: 'flutter-test-69ab6',
    authDomain: 'flutter-test-69ab6.firebaseapp.com',
    databaseURL: 'https://flutter-test-69ab6-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-69ab6.appspot.com',
  );
}
